In [1]:
import pandas as pd

In [2]:
df_country = pd.read_excel("C:/Users/dilus/Downloads/eea_t_losses-from-climate-related-extremes_p_1980-2024_v01_r01/eea_t_losses-from-climate-related-extremes_p_1980-2024_v01_r01/Data_EconomicLosses 2024_rev2025Q4_rev1.xlsx", 
                            sheet_name='Country', 
                            header=1)
df_country.head()

,Data souce,Hazard type,Price level,ISO2,Name,Losses (M€),Loss per sq.km (€),Loss per capita (€),Insured losses (M€),insured loss per sq.km (€),insured loss per capita (€),Insured losses %,FATALITIES,Fatalities per 1000 sq.km,Fatalities per 1 million inhabitants
0,CATDAT,Weather- and climate related extremes,2024,AL,Albania,577.542,20060.0,194.0,0.000,0.000000,0.000000,0.0,146,5.071029,49.167172
1,CATDAT,Weather- and climate related extremes,2024,AT,Austria,19757.403,235538.0,2417.0,3669.362,43744.331323,448.810930,19.0,2426,28.921580,296.731507
2,CATDAT,Weather- and climate related extremes,2024,BA,Bosnia and Herzegovina,5340.538,104287.0,1373.0,0.000,0.000000,0.000000,0.0,155,3.026753,39.857623
3,CATDAT,Weather- and climate related extremes,2024,BE,Belgium,18404.185,600130.0,1742.0,7609.669,248138.683275,720.290339,41.0,14827,483.483875,1403.444073
4,CATDAT,Weather- and climate related extremes,2024,BG,Bulgaria,6291.700,56684.0,801.0,99.305,894.671880,12.636762,2.0,3190,28.739774,405.933933

In [3]:
print(df_country.shape)

(164, 15)

In [4]:
print(df_country.columns.tolist())

['Data souce', 'Hazard type', 'Price level', 'ISO2', 'Name', 'Losses (M€)', 'Loss per sq.km (€)', 'Loss per capita (€)', 'Insured losses (M€)', 'insured loss per sq.km (€)', 'insured loss per capita (€)', 'Insured losses %', 'FATALITIES', 'Fatalities per 1000 sq.km', 'Fatalities per 1 million inhabitants']

In [5]:
print(df_country.isnull().sum())

Data souce                              0
Hazard type                             0
Price level                             0
ISO2                                    0
Name                                    0
Losses (M€)                             0
Loss per sq.km (€)                      0
Loss per capita (€)                     0
Insured losses (M€)                     0
insured loss per sq.km (€)              0
insured loss per capita (€)             0
Insured losses %                        0
FATALITIES                              0
Fatalities per 1000 sq.km               0
Fatalities per 1 million inhabitants    0
dtype: int64

In [6]:
# Keep only useful columns
df_country = df_country[['ISO2', 'Name', 'Losses (M€)', 'Loss per sq.km (€)', 
                          'Loss per capita (€)', 'Insured losses (M€)', 
                          'Insured losses %', 'FATALITIES',
                          'Fatalities per 1 million inhabitants']]

In [7]:
# Remove group rows (EEA/EU summaries) - keep only real countries
df_country = df_country[~df_country['ISO2'].str.contains('EEA|EU', na=False)]

In [8]:
print(df_country.shape)
df_country.head()

(152, 9)

,ISO2,Name,Losses (M€),Loss per sq.km (€),Loss per capita (€),Insured losses (M€),Insured losses %,FATALITIES,Fatalities per 1 million inhabitants
0,AL,Albania,577.542,20060.0,194.0,0.000,0.0,146,49.167172
1,AT,Austria,19757.403,235538.0,2417.0,3669.362,19.0,2426,296.731507
2,BA,Bosnia and Herzegovina,5340.538,104287.0,1373.0,0.000,0.0,155,39.857623
3,BE,Belgium,18404.185,600130.0,1742.0,7609.669,41.0,14827,1403.444073
4,BG,Bulgaria,6291.700,56684.0,801.0,99.305,2.0,3190,405.933933

In [9]:
df_year = pd.read_excel("C:/Users/dilus/Downloads/eea_t_losses-from-climate-related-extremes_p_1980-2024_v01_r01/eea_t_losses-from-climate-related-extremes_p_1980-2024_v01_r01/Data_EconomicLosses 2024_rev2025Q4_rev1.xlsx", 
                         sheet_name='Year_type', 
                         header=1)
df_year.head()

,Data Source,Hazard Type,price level,Country grouping,Category,Year,geotechnical,meteorological,hydrological,climatological,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,CATDAT,Weather- and climate related extremes,2024,EEA-38,Total loss,1980,NaN,11.453,3582.371,3898.472,NaN,NaN,NaN,NaN,NaN
1,CATDAT,Weather- and climate related extremes,2024,EEA-38,Total loss,1981,NaN,260.147,2578.625,4967.976,NaN,NaN,NaN,NaN,NaN
2,CATDAT,Weather- and climate related extremes,2024,EEA-38,Total loss,1982,NaN,32.129,5382.006,5238.366,NaN,NaN,NaN,NaN,NaN
3,CATDAT,Weather- and climate related extremes,2024,EEA-38,Total loss,1983,NaN,379.104,20513.319,418.121,NaN,NaN,NaN,NaN,NaN
4,CATDAT,Weather- and climate related extremes,2024,EEA-38,Total loss,1984,NaN,7851.821,1142.635,0.000,NaN,NaN,NaN,NaN,NaN

In [11]:
print(df_year.shape)
print(df_year.columns.tolist())

(2160, 15)
['Data Source', 'Hazard Type', 'price level', 'Country grouping', 'Category', 'Year', 'geotechnical', 'meteorological', 'hydrological', 'climatological', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']

In [12]:
# Keep only useful columns
df_year = df_year[['Year', 'Category', 'Country grouping', 
                   'meteorological', 'hydrological', 'climatological']]

In [13]:
# Keep only EEA-38 and Total loss rows
df_year = df_year[(df_year['Country grouping'] == 'EEA-38') & 
                  (df_year['Category'] == 'Total loss')]

In [14]:
# Drop the country grouping and category columns now
df_year = df_year.drop(columns=['Country grouping', 'Category'])

In [15]:
# Convert Year to integer
df_year['Year'] = df_year['Year'].astype(int)

print(df_year.shape)
df_year.head()

(180, 4)

   Year  meteorological  hydrological  climatological
0  1980          11.453      3582.371        3898.472
1  1981         260.147      2578.625        4967.976
2  1982          32.129      5382.006        5238.366
3  1983         379.104     20513.319         418.121
4  1984        7851.821      1142.635           0.000

In [16]:
print(df_year['Year'].value_counts().head())

Year
1980    4
2003    4
2005    4
2006    4
2007    4
Name: count, dtype: int64

In [18]:
print(df_year.head(10))

   Year  meteorological  hydrological  climatological
0  1980          11.453      3582.371        3898.472
1  1981         260.147      2578.625        4967.976
2  1982          32.129      5382.006        5238.366
3  1983         379.104     20513.319         418.121
4  1984        7851.821      1142.635           0.000
5  1985          32.502      2180.041        2035.837
6  1986         482.314       845.300        3247.759
7  1987        6687.078      9779.115        1362.486
8  1988         445.135      2688.515           0.000
9  1989        1782.009      1123.154        2732.347

In [25]:
# Go back to the original and check unique categories
df_year_raw = pd.read_excel("C:/Users/dilus/Downloads/eea_t_losses-from-climate-related-extremes_p_1980-2024_v01_r01/eea_t_losses-from-climate-related-extremes_p_1980-2024_v01_r01/Data_EconomicLosses 2024_rev2025Q4_rev1.xlsx", 
                         sheet_name='Year_type', 
                         header=1)

print(df_year_raw['Category'].unique())
print(df_year_raw['Country grouping'].unique())

['Total loss' 'Insured loss' 'Fatalities' 'Insured losses %']
['EEA-38' 'EEA-32' 'EU-27']

In [26]:
df_check = df_year_raw[
    (df_year_raw['Country grouping'] == 'EEA-38') & 
    (df_year_raw['Category'] == 'Total loss') &
    (df_year_raw['Year'] == 1980)
]
print(df_check)

     Data Source                                        Hazard Type  \
0         CATDAT              Weather- and climate related extremes
540       CATDAT  Weather- and climate related extremes + geotec...
1080      CATDAT              Weather- and climate related extremes
1620      CATDAT  Weather- and climate related extremes + geotec...

      price level Country grouping    Category  Year  geotechnical  \
0            2024           EEA-38  Total loss  1980           NaN
540          2024           EEA-38  Total loss  1980     58535.485
1080         2010           EEA-38  Total loss  1980           NaN
1620         2010           EEA-38  Total loss  1980     45899.912

      meteorological  hydrological  climatological  Unnamed: 10  Unnamed: 11  \
0             11.453      3582.371        3898.472          NaN          NaN
540           11.453      3582.371        3898.472          NaN       16.071
1080          10.404      2494.595        3129.491          NaN          NaN
1620          10.404      2494.595        3129.491          NaN        8.729

      Unnamed: 12  Unnamed: 13  Unnamed: 14
0             NaN          NaN          NaN
540           NaN          0.0          0.0
1080          NaN          NaN          NaN
1620          NaN          0.0          0.0

In [28]:
df_year = df_year_raw[
    (df_year_raw['Country grouping'] == 'EEA-38') & 
    (df_year_raw['Category'] == 'Total loss') &
    (df_year_raw['price level'] == 2024) &
    (df_year_raw['Hazard Type'] == 'Weather- and climate related extremes')
][['Year', 'meteorological', 'hydrological', 'climatological']].copy()

df_year = df_year.dropna(subset=['Year'])
df_year['Year'] = df_year['Year'].astype(int)
df_year = df_year.reset_index(drop=True)

print(df_year.shape)
print(df_year['Year'].value_counts().head())

(45, 4)
Year
1980    1
2003    1
2005    1
2006    1
2007    1
Name: count, dtype: int64

In [36]:
df_type = pd.read_excel("C:/Users/dilus/Downloads/eea_t_losses-from-climate-related-extremes_p_1980-2024_v01_r01/eea_t_losses-from-climate-related-extremes_p_1980-2024_v01_r01/Data_EconomicLosses 2024_rev2025Q4_rev1.xlsx", 
                         sheet_name='Type', 
                         header=1)

print(df_type.shape)
print(df_type.columns.tolist())
df_type.head()

(60, 11)
['Data Source', 'hazard type', 'Price level', 'Country grouping', 'Hazard', 'Losses (M€)', 'Insured losses (M€)', 'Fatalities', 'Losses (%)', 'Insured losses (%)', 'Fatalities (%)']

,Data Source,hazard type,Price level,Country grouping,Hazard,Losses (M€),Insured losses (M€),Fatalities,Losses (%),Insured losses (%),Fatalities (%)
0,CATDAT,Weather- and climate related extremes,2024,EEA-38,A - Geophysical events,NaN,NaN,NaN,NaN,NaN,NaN
1,CATDAT,Weather- and climate related extremes,2024,EEA-38,B - Meteorological events,237956.262,86065.433,3354.0,27.043389,50.036451,0.722148
2,CATDAT,Weather- and climate related extremes,2024,EEA-38,C - Hydrological events,414150.407,64491.717,6590.0,47.067602,37.493992,1.418889
3,CATDAT,Weather- and climate related extremes,2024,EEA-38,DH - Climatological - Heatwave events,157928.841,14085.782,448568.0,17.948387,8.189148,96.580887
4,CATDAT,Weather- and climate related extremes,2024,EEA-38,DO - Climatological - other,69869.968,7362.539,5936.0,7.940622,4.280410,1.278076

In [37]:
print(df_type.columns.tolist())

['Data Source', 'hazard type', 'Price level', 'Country grouping', 'Hazard', 'Losses (M€)', 'Insured losses (M€)', 'Fatalities', 'Losses (%)', 'Insured losses (%)', 'Fatalities (%)']

In [38]:
df_type = df_type[
    (df_type['Country grouping'] == 'EEA-38') & 
    (df_type['Price level'] == 2024) &
    (df_type['hazard type'] == 'Weather- and climate related extremes')
][['Hazard', 'Losses (M€)', 'Insured losses (M€)', 'Fatalities']].copy()

df_type = df_type.dropna(subset=['Losses (M€)'])
df_type = df_type.reset_index(drop=True)

print(df_type.shape)
df_type

(4, 4)

,Hazard,Losses (M€),Insured losses (M€),Fatalities
0,B - Meteorological events,237956.262,86065.433,3354.0
1,C - Hydrological events,414150.407,64491.717,6590.0
2,DH - Climatological - Heatwave events,157928.841,14085.782,448568.0
3,DO - Climatological - other,69869.968,7362.539,5936.0

In [45]:
df_country_type = pd.read_excel("C:/Users/dilus/Downloads/eea_t_losses-from-climate-related-extremes_p_1980-2024_v01_r01/eea_t_losses-from-climate-related-extremes_p_1980-2024_v01_r01/Data_EconomicLosses 2024_rev2025Q4_rev1.xlsx", 
                                 sheet_name='Coutry_type', 
                                 header=1)

In [47]:
df_country_type = df_country_type[
    (df_country_type['price level'] == 2024) &
    (df_country_type['Hazard Type'] == 'Weather- and climate related extremes') &
    (df_country_type['Category'] == 'Total losses')
][['ISO2', 'Name', 'meteorological', 'hydrological', 
   'Climatological (other)', 'climatological (heatwaves)']].copy()

df_country_type = df_country_type.reset_index(drop=True)

print(df_country_type.shape)
df_country_type.head()

(38, 6)

,ISO2,Name,meteorological,hydrological,Climatological (other),climatological (heatwaves)
0,AL,Albania,11.625,482.035,83.882,0.000
1,AT,Austria,4197.481,12159.282,1704.800,1695.840
2,BA,Bosnia and Herzegovina,0.795,2742.128,20.604,2577.011
3,BE,Belgium,5885.755,12231.528,0.000,286.902
4,BG,Bulgaria,743.766,5458.379,89.380,0.175

In [70]:
df_country_year = pd.read_excel("C:/Users/dilus/Downloads/eea_t_losses-from-climate-related-extremes_p_1980-2024_v01_r01/eea_t_losses-from-climate-related-extremes_p_1980-2024_v01_r01/Data_EconomicLosses 2024_rev2025Q4_rev1.xlsx", 
                                 sheet_name='Country_year', 
                                 header=1)

print(df_country_year.shape)
df_country_year.head()

(456, 51)

,Data Source,Hazard Type,price level,Category,ISO2,Name,1980,1981,1982,1983,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,CATDAT,Weather- and climate related extremes,2024,Total losses,AL,Albania,0.0,26.988,NaN,NaN,...,0.000,16.111,78.715,0.000,0.000,0.000,79.472,1.200,0.000,0.616
1,CATDAT,Weather- and climate related extremes,2024,Total losses,AT,Austria,NaN,0.212,1.849,1.742,...,0.000,30.056,1245.868,815.351,630.065,248.380,868.154,219.994,409.337,2031.507
2,CATDAT,Weather- and climate related extremes,2024,Total losses,BA,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,...,215.385,NaN,NaN,NaN,22.109,15.842,0.528,5.559,10.596,457.528
3,CATDAT,Weather- and climate related extremes,2024,Total losses,BE,Belgium,NaN,NaN,NaN,0.000,...,38.908,318.733,31.560,256.712,296.038,616.864,11653.026,945.751,121.135,202.094
4,CATDAT,Weather- and climate related extremes,2024,Total losses,BG,Bulgaria,NaN,NaN,NaN,NaN,...,1293.769,0.000,142.590,0.000,NaN,6.839,2.221,42.471,24.802,2.380

In [72]:
year_cols = [c for c in df_country_year.columns if isinstance(c, (int, float)) and 1980 <= c <= 2024]

In [74]:
df_country_year = df_country_year[
    (df_country_year['price level'] == 2024) &
    (df_country_year['Hazard Type'] == 'Weather- and climate related extremes') &
    (df_country_year['Category'] == 'Total losses')
][['ISO2', 'Name'] + year_cols].copy()

In [76]:
df_country_year = df_country_year.reset_index(drop=True)

print(df_country_year.shape)
df_country_year.head()

(38, 47)

,ISO2,Name,1980,1981,1982,1983,1984,1985,1986,1987,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,AL,Albania,0.0,26.988,NaN,NaN,NaN,0.0,NaN,NaN,...,0.000,16.111,78.715,0.000,0.000,0.000,79.472,1.200,0.000,0.616
1,AT,Austria,NaN,0.212,1.849,1.742,0.0,0.0,NaN,446.17,...,0.000,30.056,1245.868,815.351,630.065,248.380,868.154,219.994,409.337,2031.507
2,BA,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,...,215.385,NaN,NaN,NaN,22.109,15.842,0.528,5.559,10.596,457.528
3,BE,Belgium,NaN,NaN,NaN,0.000,NaN,0.0,NaN,0.00,...,38.908,318.733,31.560,256.712,296.038,616.864,11653.026,945.751,121.135,202.094
4,BG,Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1293.769,0.000,142.590,0.000,NaN,6.839,2.221,42.471,24.802,2.380

In [78]:
#Saving the cleaned datasets
df_country.to_csv('df_country.csv', index=False)
df_year.to_csv('df_year.csv', index=False)
df_type.to_csv('df_type.csv', index=False)
df_country_type.to_csv('df_country_type.csv', index=False)
df_country_year.to_csv('df_country_year.csv', index=False)

print("All files saved!")

All files saved!